title: Jared Schultz
url: "https://JaredSchultz.com"
baseurl: "/JaredSchultz"

markdown: kramdown
#ins_logo: "./bits-logo.png"

tracking_id: #

footer: yes
footer_url: "https://github.com/JaredSchultz"
footer_text: "Page design by Ankit Sultana"

sass:
    style: compressed
    sass_dir: _sass

nav:
 - name: "About"
   link: "/JaredSchultz/"
 - name: "Resume"
   link: "resume.pdf"
 - name: "Contact"
   link: "contact"
