title: Jared Schultz
url: "https://JaredSchultz.com"
baseurl: "/JaredSchultz"

markdown: kramdown
#ins_logo: "./bits-logo.png"

tracking_id: #

footer: yes
footer_url: "https://github.com/ankitsultana"
footer_text: "Template credit: Ankit Sultana"

sass:
    style: compressed
    sass_dir: _sass

nav:
 - name: "About"
   link: "/JaredSchultz/"
 - name: "Research and Papers"
   link: "research-and-papers"
 - name: "Projects"
   link: "projects"
 - name: "CV and Resume"
   link: "cv-and-resume"
